### ISSUE TITLE
Troubleshoot-Workaround for W04

### ISSUE THREAD

**Issue by LadnerJonas** [keinenclue/sasm-docker#3]
[Issue](https://github.com/Dman95/SASM/issues/102#issue-365252764) @dorianim 
To enable at-least some form of Troubleshooting follow these easy steps:

- Create a new SASM project file
- Check the debugger by pressing the Debug button (Debug window should be visible now)
- Paste the following code block in your newly created project file
```
%include "io_lin.inc" ; %include "io_win.inc" for windows users 

global fac_rec
global fac_non_rec

section .text
global CMAIN
CMAIN:
	; paste main here

	ret

fac_rec:
	; paste fac_rec here 

	ret

fac_non_rec:
	; paste fac_non_rec here

	ret
```

- Paste the main method from the homework file
- Paste your own function code in the specified fields
- Enjoy the debugger :v:

**Comment by dorianim** [comment]
Week4 is over, so I'm closing this :upside_down_face:
